%% Add this to the top of Mermaid file to apply the white theme for printing %%
%%{init: { 'theme': 'base', 'themeVariables': { 'fontSize': '13px', 'rectFill': '#f4f4f4', 'rectStroke': '#d1d1d1', 'clusterBkg': '#f9f9f9' }}}%%
